//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperEngish {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.1.0.5216")]
	internal sealed partial class SettingsSE : global::System.Configuration.ApplicationSettingsBase {
		
		private static SettingsSE defaultInstance = ((SettingsSE)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsSE())));
		
		public static SettingsSE Default {
			get {
				return defaultInstance;
			}
		}
	}
}
